name: Ocelot.Gateway

on:
  push:
    branches: [ master ]
    paths:
      - src/BuildingBlocks/**
      - src/ApiGateway/**
      - .github/workflows/ocelot-gateway.yml
      
  pull_request:
    branches: [ master ]
    paths:
      - src/BuildingBlocks/**
      - src/ApiGateway/**
      - .github/workflows/ocelot-gateway.yml

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with: 
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: jpcarpanezi/health-system-ocelot:dev
          file: src/ApiGateway/Gateway.Ocelot/Dockerfile
          context: src/
